# Site settings
title: Ambil Hikmahnya
email: aquaberrry@gmail.com
url: https://example.github.io
description: "Aquaberry adalah web yang berisi multimedia berupa gambar dan musik untuk memenuhi tugas mata kuliah Application Mobile. Mari kita ambil hikmahnya."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#219ab3'

# Footer settings
footer: Aquaberry | Ambil Hikmahnya

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: Sistem Informasi
    url: http://sif.uin-suska.ac.id/
  - title: Fakultas Sains dan Teknologi
    url: http://fst.uin-suska.ac.id/
  - title: UINSUSKA
    url: http://uin-suska.ac.id/
  - title: github
    url: https://github.com/apmobgalery14

# Build settings
markdown: kramdown
permalink: pretty
